#!/usr/bin/env bash

# Generate Java classes from .drl in resources
# mvn package -Dpackaging=kjar

# Create the application.jar to use
# mvn package -Dpackaging=jar

mvn compile org.kie:kie-maven-plugin:8.44.0.Final:build package

# Overwrite the application.jar generated by Micronaut
if [ -e build/docker/native-main/layers/app/application.jar ]
then
  cp -p target/application-0.1.jar build/docker/native-main/layers/app/application.jar
fi
if [ -e build/libs/lambda-0.1.jar ]
then
  cp -p target/application-0.1.jar build/libs/lambda-0.1.jar
fi
